# Installation et chargement de NumPy

In [1]:
#Installation et import
#!pip install numpy
import numpy as np


# Création des données avec numpy 

## Créer un numpy array avec une liste/liste de liste (matrice)

In [2]:
# Création à partir d'un liste
liste = [1, 2, 3, 4, 5]  # Définition de la liste d'élément
array_with_liste = np.array(liste)
print(array_with_liste)  # affiche le numpy array

[1 2 3 4 5]


In [ ]:
# Création à partir d'une matrice

In [3]:
# Création d'un numpy array à partir d'une liste de listes (matrice)
matrice = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
array_with_matrice = np.array(matrice)
print(array_with_matrice)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Créer un numpy array à partir des fonctions intégrées

In [4]:
#Créer un numpy array à partir de la fonction zeros
array_zeros = np.zeros((3,3))
print(array_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
#Créer un numpy array à partir de la fonction ones
array_ones = np.ones((4,2))
print(array_ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [8]:
#Créer un numpay array avec la fonction eye 
array_eye = np.eye(3)#Pour créer la matrice identité
array_eye


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
#Créer un numpay array avec la fonction arange: pour créer des nombre entre le minimum et le maximum avec un pas
array_arange = np.arange(0, 11, 2)
array_arange

array([ 0,  2,  4,  6,  8, 10])

In [12]:
#Créer un numpay array avec la fonction linspace #générer une séquence de nombre 
#entre deux valeurs données avec un nombre de points donné
array_linspace = np.linspace(0, 1, 10)#Très utile pour les graphiques
array_linspace

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [17]:
# Créer un numpy array de valeurs aléatoires avec la fonction random
array_random = np.random.random((5,4))#Utile pour initialiser les poids dans les réseaux de neurones, générer des données d'apprentissage synthétiques
print(array_random)

[[0.38460183 0.91191777 0.26433874 0.42778659]
 [0.86015894 0.33599314 0.07096604 0.53405233]
 [0.38777336 0.92685784 0.37362457 0.37665129]
 [0.66224501 0.04220367 0.09486011 0.24925666]
 [0.29675815 0.27890915 0.4802953  0.13089389]]


# Fonctions mathématiques et statistiques avec Numpy

In [20]:
#Fonction mathématiques basiques
array1=array_with_liste
array_sum = np.sum(array1)
array_mean = np.mean(array1)
array_std = np.std(array1)
array_min = np.min(array1)
array_max = np.max(array1)
array_sqrt = np.sqrt(array1)
array_abs = np.abs(array1)
array_power = np.power(array1, 2)
array_exp = np.exp(array1)
array_log = np.log(np.abs(array1))
array_sin = np.sin(array1)
array_median = np.median(array1)
array_sum

15

In [21]:
array_median

3.0

# Manipulation des matrices avec Numpy

In [22]:
# Produit matriciel
matrice = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
produit_matriciel = np.dot(array_with_matrice, array_with_matrice)
print(produit_matriciel)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [23]:
# Transposée
transposee = np.transpose(array_with_matrice)
print(transposee)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [24]:
# Inversion (pour les matrices carrées non singulières)
inverse = np.linalg.inv(array_eye)
print(inverse)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
#Déterminant
determinant=np.linalg.det(array_eye)
print(determinant)  

1.0


# Accéder  aux éléments, sélectionner, modifier et mettre à jour un numpy array

In [26]:
# Accès aux éléments
array1 = np.array([1,2,3,4,5]) 
premier_element = array1[0]
print(premier_element)


1


In [29]:
array1[2]

3

In [31]:
# Modification d'un élément
array1[0] = 15
print(array1)

[15  2  3  4  5]


In [33]:
# Sélection des éléments qui respectent une condition
condition = array1 > 5
elements_respectant_condition = array1[array1 > 2]
elements_respectant_condition

array([15,  3,  4,  5])

In [35]:
condition = array1 > 3
condition
indices = np.where(array1 > 3)
indices

(array([0, 3, 4]),)

In [36]:
array1 > 5

array([ True, False, False, False, False])

In [ ]:
# Utilisation de np.where
indices = np.where(array1 > 5)
elements_respectant_condition_np_where = array1[indices]
print(elements_respectant_condition_np_where)

In [37]:
# Mise à jour d'un numpy array
array1[condition] = 0
print(array1)

[0 2 3 0 0]


In [38]:
#  Slicing et indexation avancée
array6 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Slicing
premiere_ligne = array6[0, :]
premiere_ligne

array([1, 2, 3])

In [39]:
#Première colonne
premiere_colonne = array6[:, 0]
premiere_colonne


array([1, 4, 7])

In [40]:
#sous matrice
sous_matrice = array6[1:3, 1:3]
sous_matrice

array([[5, 6],
       [8, 9]])

In [41]:
# Indexation avancée
lignes = [0, 1]
colonnes = [1, 2]
elements_selectionnes = array6[lignes, colonnes]
elements_selectionnes

array([2, 6])

In [42]:
# Opérations élémentaires et diffusion (broadcasting)
array7 = np.array([1, 2, 3])
array8 = np.array([4, 5, 6])


# Addition élémentaire
array_addition = array7 + array8
array_addition

array([5, 7, 9])

In [43]:
# Multiplication élémentaire
array_multiplication = array7 * array8
array_multiplication


array([ 4, 10, 18])

In [44]:
# Diffusion (broadcasting)
array9 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array10 = np.array([1, 2, 3])
array9+array10

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

# Redimensionnement, append, type de données taille etc

In [48]:
#r redimensionné le numpy array
array3 = np.arange(9)
array3_redimensionne = array3.reshape((3, 3))
print(array3_redimensionne)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [47]:
array3 = np.arange(9)
array3

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [49]:
#Ajouter des éléments dans un numpy array
array1_allonge = np.append(array1, [6, 7, 8])
print(array1_allonge)

[0 2 3 0 0 6 7 8]


In [50]:
#Connaitre les caractéristiques d'un numpy array
array_with_matrice.shape#dimension de l'array 

(3, 3)

In [51]:
#Connaitre le type de l'objet
type(array_with_matrice)#type de l'objet

numpy.ndarray

In [52]:
#Connaitre le type des él
array1.dtype#type des objet

dtype('int64')

In [53]:
array7 = np.array(['1', '2', '3'])
array7.dtype

dtype('<U1')

In [ ]:
#Si vous voulez le sommaire
#pip install jupyter_contrib_nbextensions && jupyter contrib nbextension install
#pip install jlab-enhanced-cell-toolbar
#!pip install jupyterthemes

In [ ]:
#! jt -l
#!jt -t chesterish
#!jt -t chesterish
#!jt -r #reset at default

# Quizz

## Question 1:Quelle est la principale utilité de la bibliothèque NumPy en Data Science  ?

a) Gestion de base de données

b) Calcul scientifique et manipulation de tableaux

c) Création d'interfaces graphiques

d) Gestion des réseaux de neurones





## Question 2: Comment créer un tableau NumPy de dimension 1 (1D) ?

a) np.array([1, 2, 3])

b) np.arange(1, 4)

c) Les deux a et b

d) Aucune des réponses ci-dessusQuestion 


## 3: Quelle fonction NumPy permet de créer un tableau contenant uniquement des zéros ?

a) np.zeros()

b) np.ones()

c) np.eye()

d) np.full()