![programme](DLC4.png)

# Les Modules et les packages en python

##  Les Modules en python

### Créer son propre module

In [ ]:
# Création 

In [21]:
# Importer et renommer tout le module 
import description as desc 


In [8]:
# Création de la liste
chiffre_affaires = [3000, 5000, 4000, 8000, 10000]


In [10]:
# Application de la fonction 
statdescca = desc.statdescriptive(chiffre_affaires)
print(statdescca)

{'min': 3000, 'max': 10000, 'somme': 30000, 'moyenne': 6000.0}


In [12]:
# somme du chiffre d'affaire
somme_ca = desc.somme_element(chiffre_affaires)
somme_ca

30000

In [16]:
# Importer une partie
from description import statdescriptive, somme_element

In [14]:
statdescriptive(chiffre_affaires)

{'min': 3000, 'max': 10000, 'somme': 30000, 'moyenne': 6000.0}

In [17]:
somme_element(chiffre_affaires)

30000

In [ ]:
### Modules externes

## Les modules externes

Exemple de structure ici: [https://docs.python.org/fr/3/tutorial/modules.html#](https://docs.python.org/fr/3/tutorial/modules.html#)

Ensemble des modules [https://docs.python.org/3/py-modindex.html](https://docs.python.org/3/py-modindex.html)

**Quelques modules utiles en data science**


- **math**: Pour les fonctions mathématiques de base.
- **statistics** Pour faire des statistiques
- **os**: Pour interagir avec le système d'exploitation, comme la gestion des chemins de fichiers et les commandes du système d'exploitation.
- **sys**: Fournit un accès à certaines variables et fonctions qui interagissent fortement avec l'interpréteur Python.
- **json**: Pour la lecture et l'écriture de données au format JSON.
- **csv**: Pour lire et écrire des fichiers CSV.
- **datetime**: Pour manipuler les dates et les heures.
- **random**: Pour la génération de nombres aléatoires.
- **re**: Pour les expressions régulières, utiles dans le traitement de texte et le nettoyage des données.
- **sqlite3**: Pour la gestion de bases de données SQL légères.
- **pickle**: Pour la sérialisation et la désérialisation de structures de données Python.


In [ ]:
# Exemple utilisation de math

In [22]:
import math

In [27]:
print("racine carré ", math.sqrt(4))
print("cosinus: ", math.cos(90))
print("sinus: ", math.sin(90))
print("exponentiel", math.exp(90))

racine carré  2.0
cosinus:  -0.4480736161291702
sinus:  0.8939966636005579
exponentiel 1.2204032943178408e+39


In [29]:
#Exemple d'utilisation des modules statistiques
import statistics as st

In [34]:
st.mean([30,50,60])
st.mode([30,50,60])

30

In [35]:
# Exemple d'utilisation de random (choice, seed,sample,randint,shuffle)
import random

In [44]:
# Choisir une élément aléatoire dans une liste (liste de nom)
liste_nom = ["Rodrigue", "Tsunami", "Maman", "Armand"]
random.choice(liste_nom)

'Tsunami'

In [52]:
# Fixer la graine (seed)
random.seed(29393)
# Choisir une élément aléatoire dans une liste (liste de nom)
liste_nom = ["Rodrigue", "Tsunami", "Maman", "Armand"]
random.choice(liste_nom)

'Tsunami'

In [56]:
random.sample(liste_nom, 2)

['Armand', 'Tsunami']

In [61]:
# Aléatoire float (random.random)
random.random()

0.5872614786638335

In [65]:
# Aléatoire integer 
random.randint(1,100)

80

In [ ]:
# Choisir un nombre d'élément à partir d'une liste et choisir un nombre précis

In [78]:
# Mélanger aléatoirement des données dans une liste (shuffle)
random.shuffle(liste_nom)
liste_nom

['Maman', 'Tsunami', 'Rodrigue', 'Armand']

## Les packages en python

Lien pour en sarvoir plus [https://packaging.python.org/en/latest/tutorials/packaging-projects/](https://packaging.python.org/en/latest/tutorials/packaging-projects/)

## utilisation de mon package

In [80]:
import monpackage.module as md

In [81]:
from monpackage import module


In [84]:
# liste des packages disponibles
!pip list

Package                       Version
----------------------------- ------------
aiobotocore                   2.5.0
aiofiles                      22.1.0
aiohttp                       3.8.5
aioitertools                  0.7.1
aiosignal                     1.2.0
aiosqlite                     0.18.0
alabaster                     0.7.12
anaconda-anon-usage           0.4.2
anaconda-catalogs             0.2.0
anaconda-client               1.12.1
anaconda-cloud-auth           0.1.3
anaconda-navigator            2.5.0
anaconda-project              0.11.1
anyio                         3.5.0
appdirs                       1.4.4
applaunchservices             0.3.0
appnope                       0.1.2
appscript                     1.1.2
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.3
astroid                       2.14.2
astropy                       5.1
asttokens                     2.0.5
async-timeout                 4.0.2
atomicwrites 

Trouver les packages disponibles ici: [https://pypi.org/](https://pypi.org/)

In [90]:
# Installer un package
!≠

In [89]:
# importer un package
import numpy as np 


In [94]:
#from monpackage import description.statdescriptive

from monpackage.description import statdescriptive

# QCM

## Question 1
**Quelle est la principale différence entre un module et un package en Python ?**
- **A.** Un module est une collection de fonctions, tandis qu'un package est une collection de modules.
- **B.** Un module est un fichier contenant du code Python, tandis qu'un package est un dossier contenant un ou plusieurs modules.
- **C.** Un module ne peut pas être importé, tandis qu'un package peut être importé dans d'autres scripts Python.
- **D.** Il n'y a pas de différence; les termes module et package sont interchangeables en Python.

## Question 2
**Considérons le package `mypackage` contenant deux modules : `module1` et `module2`. Comment importeriez-vous une fonction nommée `myfunction` du `module1` ?**
- **A.** `import mypackage.module1.myfunction`
- **B.** `from mypackage import module1.myfunction`
- **C.** `from mypackage.module1 import myfunction`
- **D.** `import myfunction from mypackage.module1`


# Travailler avec les fichiers

[https://docs.python.org/fr/3/library/functions.html#open](https://docs.python.org/fr/3/library/functions.html#open)

## Open

In [ ]:
# Ecrire dans le fichier et créer le fichier (première approche)

In [95]:
f = open("resultat.txt", "w")
f.write("Bonjour")
f.close()

In [96]:
f = open("resultat.txt", "r")
f.read()


'Bonjour'

In [ ]:
f.close()

In [ ]:
# Lecture première approche




In [98]:
# Ecriture deuxième approche (with)
with open("resultatbisv2.txt", "w") as f:
    for i in range(0,10):
        f.write(f"La valeur est {i}\n")


In [99]:
# Lecture deuxième approche (readlines et read().splitlines())
with open("resultatbisv2.txt", "r") as f:
    resultat = f.readlines()
resultat

['La valeur est 0\n',
 'La valeur est 1\n',
 'La valeur est 2\n',
 'La valeur est 3\n',
 'La valeur est 4\n',
 'La valeur est 5\n',
 'La valeur est 6\n',
 'La valeur est 7\n',
 'La valeur est 8\n',
 'La valeur est 9\n']

In [ ]:
# Importer avec la technique des listes en compréhension

# Bien démarrer avec Numpy

## Bien démarrer avec une dimensions (Create)

In [ ]:
# shape

In [100]:
# importation 
import numpy as np


In [101]:
# Création d'un nd array à une dimension à partir d'une liste
tableau_dim1 = np.array([33,4,4,5,6,4])
tableau_dim1

array([33,  4,  4,  5,  6,  4])

In [110]:
tableau_dim1 = np.array([[33,4,4,5,6,4],[33,4,4,5,6,4],[33,4,4,5,6,4]])
tableau_dim1.shape

(3, 6)

In [105]:
tableau_dim1.shape

tuple

In [103]:
tableau_dim1.size

6

In [ ]:
# shape de l'objet


In [ ]:
#Nombre d'élément dans le tableau size de l'objet


In [ ]:
# Attributs importants: shape et size

## Créer un numpy array à partir des fonctions intégrées

In [112]:
# Tableau avec des zéros (np.zeros)
np.zeros??
tableau_zero = np.zeros((2,2))
tableau_zero

array([[0., 0.],
       [0., 0.]])

In [113]:
# Tableau avec des uns (np.ones)
tableau_one = np.ones((2,2))
tableau_one

array([[1., 1.],
       [1., 1.]])

In [115]:
# Créer une matrice identité avec np.eye()
tableau_eye = np.eye(3)
tableau_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#Créer un numpy array avec la fonction arange: pour créer des nombre entre le minimum et le maximum avec un pas

In [117]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [122]:
#Créer un numpay array avec la fonction linspace #générer une séquence de nombre # Très utile pour les graphiques
#entre deux valeurs données avec un nombre de points donné
np.linspace(1,1000,1000)

array([   1.,    2.,    3.,    4.,    5.,    6.,    7.,    8.,    9.,
         10.,   11.,   12.,   13.,   14.,   15.,   16.,   17.,   18.,
         19.,   20.,   21.,   22.,   23.,   24.,   25.,   26.,   27.,
         28.,   29.,   30.,   31.,   32.,   33.,   34.,   35.,   36.,
         37.,   38.,   39.,   40.,   41.,   42.,   43.,   44.,   45.,
         46.,   47.,   48.,   49.,   50.,   51.,   52.,   53.,   54.,
         55.,   56.,   57.,   58.,   59.,   60.,   61.,   62.,   63.,
         64.,   65.,   66.,   67.,   68.,   69.,   70.,   71.,   72.,
         73.,   74.,   75.,   76.,   77.,   78.,   79.,   80.,   81.,
         82.,   83.,   84.,   85.,   86.,   87.,   88.,   89.,   90.,
         91.,   92.,   93.,   94.,   95.,   96.,   97.,   98.,   99.,
        100.,  101.,  102.,  103.,  104.,  105.,  106.,  107.,  108.,
        109.,  110.,  111.,  112.,  113.,  114.,  115.,  116.,  117.,
        118.,  119.,  120.,  121.,  122.,  123.,  124.,  125.,  126.,
        127.,  128.,

In [ ]:
## Créer un numpy array de valeurs aléatoires avec la fonction random avec np.random.random

In [123]:
np.random??

In [ ]:
# nombre aléatoire distribuée suivant une loi aléatoire
#fixer la graine avec seed de random

## Accéder  aux éléments, sélectionner (Read)

In [128]:
# Accès aux éléments
# Création d'un nd array à une dimension à partir d'une liste
tableau_dim1 = np.array([33,4,4,5,6,4,3,11])
tableau_dim1

array([33,  4,  4,  5,  6,  4,  3, 11])

In [126]:
tableau_dim1[-1]

4

In [134]:
# Sélection des éléments qui respectent une condition
tableau_dim1[tableau_dim1 >6]

array([33, 11])

In [ ]:
# utilisation de np.where()
np.where(tableau_dim1>10)
nb_superieur_10 = tableau_dim1[np.where(tableau_dim1>10)]
nb_superieur_10

In [ ]:
# Recupérer des éléments à partir des indices

## Modifier et mettre à jour un numpy array (Update)

In [ ]:
# Modification d'un élément


## Fonctions mathématiques et statistiques avec Numpy

# Quiz 
## Question 1:Quelle est la principale utilité de la bibliothèque NumPy en Data Science  ?

a) Gestion de base de données

b) Calcul scientifique et manipulation de tableaux

c) Création d'interfaces graphiques

d) Gestion des réseaux de neurones





## Question 2: Comment créer un tableau NumPy de dimension 1 (1D) ?

a) np.array([1, 2, 3])

b) np.arange(1, 4)

c) Les deux a et b

d) Aucune des réponses ci-dessusQuestion 


## 3: Quelle fonction NumPy permet de créer un tableau contenant uniquement des zéros ?

a) np.zeros()

b) np.ones()

c) np.eye()


# Exercices de Programmation

## Exercice 1 : Création et Utilisation d'un Module pour la Gestion de Contacts
**Objectif** : Développer un module pour la gestion d'un carnet d'adresses, l'utiliser pour ajouter des contacts, et enregistrer ces contacts dans un fichier texte.

**Instructions** :
1. **Créer un Module `gestion_contacts`** : Ce module doit contenir des fonctions pour ajouter un nouveau contact (nom, numéro de téléphone, email) et pour lister tous les contacts.
2. **Utiliser le Module dans un Script** : Dans un script principal, utilisez ce module pour ajouter quelques contacts.
3. **Sauvegarde des Contacts** : Après l'ajout des contacts, enregistrez la liste des contacts dans un fichier texte `contacts.txt` en utilisant les fonctions de gestion de fichiers.

## Exercice 2 : Analyse de Données avec Numpy et Sauvegarde des Résultats
**Objectif** : Effectuer des opérations statistiques de base sur un ensemble de données avec numpy et enregistrer les résultats dans un fichier texte.

**Instructions** :
1. **Génération de Données** : Utilisez numpy pour générer un ensemble de données composé de 100 nombres aléatoires.
2. **Analyse Statistique** : Calculez la moyenne, la médiane, et l'écart-type de cet ensemble.
3. **Écriture des Résultats** : Enregistrez les résultats calculés dans un fichier `analyse_stats.txt`, en indiquant clairement chaque mesure.

## Exercice 3 : Module pour la Conversion de Températures et Enregistrement en Fichier Texte
**Objectif** : Développer un module simple pour convertir les températures entre Celsius et Fahrenheit, puis enregistrer ces valeurs dans un fichier texte.

**Instructions** :
1. **Création d'un Module de Conversion** : Créez un module nommé `convert_temp` qui contient deux fonctions. La première fonction convertit la température de Celsius en Fahrenheit, et la deuxième fait l'inverse.
2. **Conversion de Températures** : Utilisez votre module pour convertir une liste de températures en Celsius en Fahrenheit. Vous pouvez utiliser une liste fixe de températures pour simplifier l'exercice (par exemple, 0, 10, 20, 30 degrés Celsius).
3. **Sauvegarde des Températures Converties** : Écrivez les températures originales en Celsius et leurs équivalents en Fahrenheit dans un fichier texte nommé `temp_conversions.txt`. Le format du fichier peut être simple, par exemple : "0°C - 32°F".

